version: '2'
services:
    monitor-app:
        image: monitor
        external_links:
            - monitor-mysql:mysql
            - monitor-elasticsearch:elasticsearch
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/monitor?useUnicode=true&characterEncoding=utf8&useSSL=false
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticsearch:9300
        ports:
            - 8080:8080
    monitor-mysql:
        extends:
            file: mysql.yml
            service: monitor-mysql
    monitor-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: monitor-elasticsearch
